server {
    listen 14201 ssl;
    server_name coinswap_maker;

    include /etc/nginx/mynode/mynode_ssl_params.conf;
    include /etc/nginx/mynode/mynode_ssl_cert_key.conf;

    access_log /var/log/nginx/access_coinswap_maker.log;
    error_log /var/log/nginx/error_coinswap_maker.log;

    location / {
        proxy_pass http://127.0.0.1:14200;

        include /etc/nginx/mynode/mynode_ssl_proxy_params.conf;
    }
}
